version: '3'
services:
  golang:
    build: .
    environment:
      go-repository-pattern_ENV: development
    volumes:
      - .:/go/src/github.com/mochizukikotaro/go-repository-pattern
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: yes
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypw
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
volumes:
  data: